apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
      readUser:
      readPass:

---        
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    run: gateway 
spec:
  type: NodePort
  clusterIP: 10.96.4.4
  ports:
  - name: rtsp 
    port: 8554
    targetPort: 8554
    nodePort: 30554
    protocol: TCP
  selector:
    app: gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        
    spec:
      containers:
        - name: proxy
          image: rtsp-sidecar-proxy:latest
          imagePullPolicy: Never
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
            - name: rtp
              protocol: UDP
              containerPort: 8050
            - name: rtcp
              protocol: UDP
              containerPort: 8051
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1337
            runAsGroup: 1337
            privileged: false
          volumeMounts:
            - name: proxy-config
              mountPath: /tmp
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-cfg
