---        
apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    run: monitor
spec:
  clusterIP: 10.96.3.3
  ports:
  - name: rtsp 
    port: 8554
    targetPort: 8554
    protocol: TCP
  selector:
    app: monitor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: monitor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: rtsp
          image: rtsp-simple-server:latest
          imagePullPolicy: Never
          env:
            - name: RTSP_RTSPPORT
              value: "8554"
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
