apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    command:
    - sleep
    - "36000"
  restartPolicy: Always
