---        
apiVersion: v1
kind: Service
metadata:
  name: camera
  labels:
    run: camera
spec:
  clusterIP: 10.96.2.2
  ports:
  - name: rtsp 
    port: 554
    targetPort: 8554
    protocol: TCP
  selector:
    app: camera

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
  labels:
    app: camera
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp
          image: rtsp-simple-server:latest
          imagePullPolicy: Never
          env:
            - name: RTSP_RTSPPORT
              value: "554"
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 554
            - name: rtp
              protocol: UDP
              containerPort: 8000
            - name: rtcp
              protocol: UDP
              containerPort: 8001

        - name: ffmpeg
          image: ffmpeg-image
          imagePullPolicy: Never
