apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8554
    hostPort: 8554
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 8050
    hostPort: 8050
    protocol: udp # Optional, defaults to tcp
  - containerPort: 8051
    hostPort: 8051
    protocol: udp # Optional, defaults to tcp
