---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
      readUser:
      readPass:
---
apiVersion: v1
kind: Service
metadata:
  name: facepass-service
  labels:
    run: facepass
spec:
  type: NodePort
  clusterIP: 10.96.5.5
  ports:
  - name: rtsp
    port: 554
    targetPort: 8554
    nodePort: 32555
    protocol: TCP
  selector:
    app: facepass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facepass
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facepass
  template:
    metadata:
      labels:
        app: facepass
    spec:
      initContainers:
        - name: init
          image: init:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
              - ALL
            privileged: false

      containers:

        - name: proxy
          image: rtsp-sidecar-proxy:latest
          imagePullPolicy: Never
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
            - name: rtp
              protocol: UDP
              containerPort: 8050
            - name: rtcp
              protocol: UDP
              containerPort: 8051
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1337
            runAsGroup: 1337
            privileged: false
          volumeMounts:
            - name: proxy-config
              mountPath: /tmp

        - name: facepass 
          image: facepass:latest
          imagePullPolicy: Never
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: OPENCV_FFMPEG_CAPTURE_OPTIONS
              value: "rtsp_transport;udp"
            - name: RTSP_TRANSPORT
              value: "tcp"
            - name: INPUT_RTSP_URL
              value: "rtsp://10.96.2.2:554/camera"
            - name: OUTPUT_RTSP_URL
              value: "rtsp://10.96.3.3:8554/monitor"
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-cfg 
